### ISSUE TITLE
Fix missing /usr/src/app/openapi_server/openapi/openapi.yaml

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/date-annotator-stub#1]
### Problem description

When using the image `nlpsandbox/date-annotator-stub:1.0.0`, I get the following error:

```
$ docker-compose up
Pulling date-annotator (nlpsandbox/date-annotator-stub:latest)...
latest: Pulling from nlpsandbox/date-annotator-stub
4c0d98bf9879: Pull complete
bb7efd68e949: Pull complete
c9f2eedb88b6: Pull complete
5bade50d9d7c: Pull complete
d6eb1c1fc3e5: Pull complete
4149d824d058: Pull complete
46570b765974: Pull complete
9c03061cff3a: Pull complete
f6aceb81c7ee: Pull complete
Digest: sha256:3bfc45e182cdcf919f830a51a71d07ffaff375c5b08c2e3c645a68ab25238ed5
Status: Downloaded newer image for nlpsandbox/date-annotator-stub:latest
Creating date-annotator-stub ... done
Attaching to date-annotator-stub
date-annotator-stub | Traceback (most recent call last):
date-annotator-stub |   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
date-annotator-stub |     return _run_code(code, main_globals, None,
date-annotator-stub |   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
date-annotator-stub |     exec(code, run_globals)
date-annotator-stub |   File "/usr/src/app/openapi_server/__main__.py", line 19, in <module>
date-annotator-stub |     main()
date-annotator-stub |   File "/usr/src/app/openapi_server/__main__.py", line 11, in main
date-annotator-stub |     app.add_api('openapi.yaml',
date-annotator-stub |   File "/usr/local/lib/python3.9/site-packages/connexion/apps/flask_app.py", line 57, in add_api
date-annotator-stub |     api = super(FlaskApp, self).add_api(specification, **kwargs)
date-annotator-stub |   File "/usr/local/lib/python3.9/site-packages/connexion/apps/abstract.py", line 144, in add_api
date-annotator-stub |     api = self.api_cls(specification,
date-annotator-stub |   File "/usr/local/lib/python3.9/site-packages/connexion/apis/abstract.py", line 75, in __init__
date-annotator-stub |     self.specification = Specification.load(specification, arguments=arguments)
date-annotator-stub |   File "/usr/local/lib/python3.9/site-packages/connexion/spec.py", line 153, in load
date-annotator-stub |     return cls.from_file(spec, arguments=arguments)
date-annotator-stub |   File "/usr/local/lib/python3.9/site-packages/connexion/spec.py", line 106, in from_file
date-annotator-stub |     spec = cls._load_spec_from_file(arguments, specification_path)
date-annotator-stub |   File "/usr/local/lib/python3.9/site-packages/connexion/spec.py", line 90, in _load_spec_from_file
date-annotator-stub |     with specification.open(mode='rb') as openapi_yaml:
date-annotator-stub |   File "/usr/local/lib/python3.9/pathlib.py", line 1241, in open
date-annotator-stub |     return io.open(self, mode, buffering, encoding, errors, newline,
date-annotator-stub |   File "/usr/local/lib/python3.9/pathlib.py", line 1109, in _opener
date-annotator-stub |     return self._accessor.open(self, flags, mode)
date-annotator-stub | FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/app/openapi_server/openapi/openapi.yaml'
date-annotator-stub exited with code 1
```

**Comment by tschaffter** [comment]
The `edge` tag has the same issue.

However running `docker-compose up --build` works:

```
date-annotator-stub |  * Serving Flask app "__main__" (lazy loading)
date-annotator-stub |  * Environment: production
date-annotator-stub |    WARNING: This is a development server. Do not use it in a production deployment.
date-annotator-stub |    Use a production WSGI server instead.
date-annotator-stub |  * Debug mode: off
date-annotator-stub |  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
```

Why?

**Comment by tschaffter** [comment]
```
$ docker run --rm -p 8080:8008 nlpsandbox/date-annotator-stub
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/openapi_server/__main__.py", line 19, in <module>
    main()
  File "/usr/src/app/openapi_server/__main__.py", line 11, in main
    app.add_api('openapi.yaml',
  File "/usr/local/lib/python3.9/site-packages/connexion/apps/flask_app.py", line 57, in add_api
    api = super(FlaskApp, self).add_api(specification, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/connexion/apps/abstract.py", line 144, in add_api
    api = self.api_cls(specification,
  File "/usr/local/lib/python3.9/site-packages/connexion/apis/abstract.py", line 75, in __init__
    self.specification = Specification.load(specification, arguments=arguments)
  File "/usr/local/lib/python3.9/site-packages/connexion/spec.py", line 153, in load
    return cls.from_file(spec, arguments=arguments)
  File "/usr/local/lib/python3.9/site-packages/connexion/spec.py", line 106, in from_file
    spec = cls._load_spec_from_file(arguments, specification_path)
  File "/usr/local/lib/python3.9/site-packages/connexion/spec.py", line 90, in _load_spec_from_file
    with specification.open(mode='rb') as openapi_yaml:
  File "/usr/local/lib/python3.9/pathlib.py", line 1241, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/local/lib/python3.9/pathlib.py", line 1109, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/app/openapi_server/openapi/openapi.yaml'
```

But

```
$ docker build -t plop .
$ docker run --rm -p 8080:8008 plop
```

**Comment by tschaffter** [comment]
The issue was due to a mistake in *.gitignore*. It's now fixed.
